XTrain = rand(24,24,256,100);
YTrain = categorical(rand(100,1) > 0.5);
dsTrain = augmentedImageDatastore([size(XTrain,1) size(XTrain,2) size(XTrain,3)], XTrain,YTrain');

layers2 = [ image3dInputLayer([ 24 24 256]) ...
        convolution3dLayer([3 3 3], 16, 'Padding', 1) ...
        reluLayer() ...
        convolution3dLayer([3 3 3], 16, 'Padding', 1) ...
        reluLayer() ...
        maxPooling3dLayer(2, 'Stride', 2) ...
        convolution3dLayer([3 3 3], 32, 'Padding', 1) ...
        reluLayer() ...
        convolution3dLayer([3 3 3], 32, 'Padding', 1) ...
        reluLayer() ...
        maxPooling3dLayer(2, 'Stride', 2) ...
        convolution3dLayer([3 3 3], 64, 'Padding', 1) ...
        reluLayer() ...
        convolution3dLayer([3 3 3], 64, 'Padding', 1) ...
        reluLayer() ...    
        convolution3dLayer([3 3 3], 64, 'Padding', 1) ...
        reluLayer() ...    
        maxPooling3dLayer(2, 'Stride', 2) ...
        fullyConnectedLayer(1024) ...
        dropoutLayer(0.5) ...
        fullyConnectedLayer(1024) ...
        dropoutLayer(0.5) ...
        fullyConnectedLayer(2) ...
        softmaxLayer() ...
        classificationLayer ];
