clear
load child_mind_spec.mat;
layers = vgg16 ('Weights', 'none');

subsample = 8;
layers2 = rescalenetwork(layers, subsample, 2, [26:32]);

layers2 = [ imageInputLayer([ 28 28 3]) ...
            convolution2dLayer(3, 64) ...
            reluLayer() ...
            maxPooling2dLayer(2, 'Stride', 2) ...
            fullyConnectedLayer(2) ...
            softmaxLayer() ...
            classificationLayer ];

% resize images
YFinal = categorical(cellfun(@(x)x(4), YOri));
ds = augmentedImageDatastore([size(XOriSpec,1) size(XOriSpec,2) size(XOriSpec,3)],XOriSpec,YFinal);

%% options
miniBatchSize = 1024; % power of 2
valFrequency = floor(length(XOriSpec)/miniBatchSize);
options = trainingOptions('sgdm', ...
    'MiniBatchSize',miniBatchSize, ...
    'MaxEpochs',1, ...
    'InitialLearnRate', 0.01, ... % 3e-4, Change learning schedule every 30 epochs, divide by 10
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropFactor', 0.1, ...
    'LearnRateDropPeriod', 10, ... % or 30
    'ValidationData', ds, ...
    'ValidationFrequency', valFrequency, ...
    'Shuffle','every-epoch', ...
    'Verbose',false, ...
    'Plots','training-progress');
net = trainNetwork(ds,layers2,options);